workspace:
  base: /go
  path: src/github.com/cdreier/mind-surf

pipeline:
  frontend:
    image: node
    commands:
      - cd frontend
      - npm install
      - npm run build

  build:
    image: drailing/go_packr_zip
    commands:
      - echo ${DRONE_REPO_NAME}
      - echo ${DRONE_BRANCH}
      - go get
      - go test
      - GOOS=linus; GOARCH=amd64; packr build

