workspace:
  base: /go
  path: src/github.com/cdreier/mind-surf

pipeline:
  frontend:
    image: node
    commands:
      - cd frontend
      - npm install
      - npm run build

  build:
    image: drailing/go_packr_zip
    commands:
      - go get
      - go test
      - GOOS=linux; GOARCH=amd64; packr build -o ${DRONE_REPO_NAME}-${DRONE_BRANCH}-linux-amd64
      - GOOS=darwin; GOARCH=amd64; packr build -o ${DRONE_REPO_NAME}-${DRONE_BRANCH}-darwin-amd64
      - GOOS=windows; GOARCH=amd64; packr build -o ${DRONE_REPO_NAME}-${DRONE_BRANCH}-win-amd64.exe
      - ls

