workspace:
  base: /go
  path: src/github.com/cdreier/mind-surf

pipeline:
  frontend:
    image: node
    commands:
      - cd frontend
      - npm install
      - npm run build

  build:
    image: golang
    commands:
      - go get
      - go install github.com/gobuffalo/packr
      - packr build
